Feat/sprint3
InseeFrLab/edt pull request #12
Opened 2022-11-18 15:55 UTC by PaulBOURGEAIS

2022-11-21 12:06 UTC, MichaelC67 requested changes

2022-11-21 12:06 UTC, MichaelC67 commented on src/service/survey-service.ts
> +    lastName = "LASTNAME",
Use uppercase ?
https://google.github.io/styleguide/jsguide.html#features-objects-enums
(the same for L13/L14)

2022-11-21 13:03 UTC, PaulBOURGEAIS commented on src/pages/help/Help.tsx
> +                placeholder="Saisissez une activité"
Code here is temporar, it's just for tests purpose

2022-11-21 13:04 UTC, PaulBOURGEAIS commented on src/pages/work-time/weekly-planner/WeeklyPlanner.tsx
> +                    page="3"
The weekly planner is page 3 of the work-time-survey.json

2022-11-22 17:28 UTC, MichaelC67 approved these changes

2022-11-29 12:31 UTC, MichaelC67 commented
Waiting the CI/CD to be fixed to merge if SonarCLoud analysis is ok.

2022-12-12 20:15 UTC, MichaelC67 approved these changes

2022-12-19 22:16 UTC, merged