Fix/weekly planner
InseeFrLab/edt pull request #60
Opened 2024-09-10 12:37 UTC by MailineN

2024-09-12 10:41 UTC, Grafikart requested changes
Quelques commentaires à ajouter et des console.log à retirer

2024-09-12 10:41 UTC, Grafikart commented on package.json
> +        "start-with-lib": "concurrently \"yarn run dev\" \"cd ./node_modules/@inseefrlab/lunatic-edt && tsc-watch\""
Cette commande me semble étrange, lunatic-edt devrait déjà être build

2024-09-12 10:41 UTC, Grafikart commented on src/components/commons/SurveyPage/SurveyPageStep/SurveyPageStep.tsx
> +            if (validateButton) {
Un early return réduirait l'imbrication ici

2024-09-12 10:41 UTC, Grafikart commented on src/pages/who-are-you/WhoAreYou.tsx
>  import React, { useCallback } from "react";
L'import React ne devrait pas être là.

2024-09-12 10:41 UTC, Grafikart commented on src/pages/who-are-you/WhoAreYou.tsx
> +        console.log("validate button");
console log oublié ?

2024-09-12 10:41 UTC, Grafikart commented on src/pages/work-time/weekly-planner/WeeklyPlanner.tsx
> +            console.log('CallbackHolder', callbackHolder.getData());
Console.log oublié ?

2024-09-12 10:41 UTC, Grafikart commented on src/pages/work-time/weekly-planner/utils.ts
> +export const createDataWeeklyPlanner = (data: LunaticData) => {
Ajouter un commentaire pour expliquer le rôle / context de cette méthode. Ajouter un type de retour

2024-09-12 10:41 UTC, Grafikart commented on src/service/api-service/putRemoteData.ts
> +    console.log("requestPutSurveyData", tempData);
console log a supprimer je pense non ?

2024-09-12 10:41 UTC, Grafikart commented on src/service/survey-service.ts
> +    console.log("SaveData", data);
console.log a supprimer

2024-09-12 10:41 UTC, Grafikart commented on src/service/survey-service.ts
> +        //TODO: Fix this
Expliquer ce qu'il faut fix

2024-09-12 10:41 UTC, Grafikart commented on src/service/survey-service.ts
> +    console.log("validateAllGroup", personAct);
console.log oublié ?

2024-09-17 13:07 UTC, MailineN commented on src/service/survey-service.ts
> +        //TODO: Fix this
Fait ailleurs

2024-09-17 13:17 UTC, MailineN commented on package.json
> +        "start-with-lib": "concurrently \"yarn run dev\" \"cd ./node_modules/@inseefrlab/lunatic-edt && tsc-watch\""
C'est pour pouvoir modifier lunatic-edt en même temps et tester en direct

2024-09-17 13:19 UTC, merged