Fix/custom activities
InseeFrLab/edt pull request #75
Opened 2024-10-31 10:19 UTC by MailineN

- Correction de l'ajout d'activités non prévues dans les referentiels 
- (Re)ajout de la variable ISVALIDATED (demande métier) 
- Ajout d'une sauvegarde intermédiaire lors de l'ajout d'une activité (demande métier) 
- Nettoyage de code à divers endroits

2024-11-08 15:53 UTC, Grafikart requested changes

2024-11-08 15:53 UTC, Grafikart commented on src/pages/activity/activity-or-route-planner/activity-duration/ActivityDuration.tsx
> +    let endTimeDay: Dayjs = dayjs();
Attention cela crée une nouvelle date à chaque rendu. Une variable globale "today" pourait améliorer les choses.

2024-11-08 15:53 UTC, Grafikart commented on src/pages/activity/activity-or-route-planner/with-screen/WithScreen.tsx
> +            );
Pourquoi avoir retirer le validate ici ?

2024-11-12 08:48 UTC, MailineN commented on src/pages/activity/activity-or-route-planner/with-screen/WithScreen.tsx
> +            );
La fonction merge les données récupérées par getData() (qui sont de toutes manière modifiées quand l'enquêté répond) avec celles du callbackHolder.getData() de lunatic qui a la priorité sur le premier. 
Dans le cas des activités custom (géré par lunatic-edt) vu que l'on "sort" du flow normal, les données ne sont pas enregistrées

2024-11-14 14:19 UTC, merged